_target_: tracklab.wrappers.DanceTrackEvaluator

eval_set: "val"

cfg:
  eval_mot: True

  min_tracklet_length: 0

  bbox_column_for_eval: "bbox_ltwh"  # which bbox column to use for evaluation: {"bbox_ltwh", "track_bbox_ltwh", "pred_bbox_ltwh", ...}
  print_by_video: True

  mot_trackers_folder: "eval/mot"
  mot_gt_folder: ${dataset.dataset_path}/${dataset.eval_set}

  use_parallel: True
  num_parallel_cores: ${num_cores}

  mot:
    dataset_path: ${dataset.dataset_path}
    use_ignore_regions: True
    ignore_iou_thres: 0.1
    vis_threshold: 0.1
