dataset_path: ${data_dir}  # FIXME needed for detector and reid instantiate(), even if not used when using external video
nvid: -1                                    # "-1" to process all the videos
nframes: -1                                 # "-1" to process all the frames for each video. evaluation is disabled if nframes != -1
eval_set: "val"

vids_dict:                                  # video names to use for each split (train/val/test/..). This is an example, the exact split name depends on the dataset
  train: []
  val: []  # leave empty to use all videos
  test: []

track_eval:
  dataset_class: MotChallenge2DBox
