name: "SoccerNet"
nickname: "sn"
fig_size: [384, 128]
mask_size: [64, 32]
max_crop_size: [256, 128]
masks_mode: "pose_on_img_crops"
enable_human_parsing_labels: False
eval_metric: "mot_intra_video"  # {"mot_inter_intra_video", "mot_intra_video", "mot_inter_video"}
columns: ["role", "team", "jersey_number"]

multi_video_queries_only: False  # will be set to True by default if eval_metric is "mot_inter_video"
train:
  set_name: "train"
  min_vis: 0.3
  min_h: 30
  min_w: 30
  min_samples_per_id: 4
  ######## 4 - 12 ##########
  max_samples_per_id: 15
  max_total_ids: -1
test:
  set_name: "valid"
  min_vis: 0.
  min_h: 0
  min_w: 0
  min_samples_per_id: 4
  ########## 6 - 15 ##########
  max_samples_per_id: 10
  max_total_ids: -1
  ratio_query_per_id: 0.2